In [81]:
import pandas as pd; import numpy as np ; import matplotlib.pyplot as plt ; import seaborn as sns;
from numpy import argmax;

from sklearn.datasets import make_classification as mc;
from sklearn.datasets import load_iris;
from sklearn.datasets import load_diabetes

from sklearn.metrics import precision_recall_curve as prc;
from sklearn.metrics import roc_curve as roc;
from sklearn.metrics import classification_report as report;
from sklearn.metrics import roc_auc_score;
from sklearn.metrics import precision_score;
from sklearn.metrics import recall_score;
from sklearn.metrics import get_scorer_names

from sklearn.linear_model import LogisticRegression as LR;
from sklearn.linear_model import LinearRegression as LinReg;


from sklearn.model_selection import train_test_split;
from sklearn.model_selection import cross_validate;
from sklearn.model_selection import KFold;

from sklearn.preprocessing import OneHotEncoder as OHE;
from sklearn.preprocessing import StandardScaler as SC;

from sklearn.ensemble import RandomForestClassifier as RFC;

from sklearn.svm import SVC;
from sklearn.svm import SVR;

from yellowbrick.classifier import ROCAUC;
from yellowbrick.classifier import PrecisionRecallCurve;

from sklearn.model_selection import LeavePOut;

from sklearn.pipeline import make_pipeline;

In [ ]:
import warnings as yapping
yapping.filterwarnings('ignore')

#1. Изучите разбиение Leave-P-Out. Продемонстрируйте работу этого алгоритма на примере из лабораторной работы.

In [ ]:
x,y = load_iris(as_frame=True).data,load_iris().target
lpo = LeavePOut(2)
print(f'Столько сплитов: {lpo.get_n_splits(x)}')
for i, (train_index, test_index) in enumerate(lpo.split(x)):
    print(f"Fold {i}:")
    #print(f"  Train: index={train_index}")
    #print(f"  Test:  index={test_index}")
    m = LR().fit(x.values[train_index],y[train_index])
    print('Accuracy:',m.score(x.values[test_index],y[test_index]))

Streaming output truncated to the last 5000 lines.
Fold 8675:
Accuracy: 1.0
Fold 8676:
Accuracy: 1.0
Fold 8677:
Accuracy: 1.0
Fold 8678:
Accuracy: 1.0
Fold 8679:
Accuracy: 1.0
Fold 8680:
Accuracy: 1.0
Fold 8681:
Accuracy: 1.0
Fold 8682:
Accuracy: 1.0
Fold 8683:
Accuracy: 1.0
Fold 8684:
Accuracy: 1.0
Fold 8685:
Accuracy: 1.0
Fold 8686:
Accuracy: 1.0
Fold 8687:
Accuracy: 1.0
Fold 8688:
Accuracy: 1.0
Fold 8689:
Accuracy: 1.0
Fold 8690:
Accuracy: 1.0
Fold 8691:
Accuracy: 1.0
Fold 8692:
Accuracy: 1.0
Fold 8693:
Accuracy: 0.5
Fold 8694:
Accuracy: 1.0
Fold 8695:
Accuracy: 1.0
Fold 8696:
Accuracy: 1.0
Fold 8697:
Accuracy: 1.0
Fold 8698:
Accuracy: 1.0
Fold 8699:
Accuracy: 1.0
Fold 8700:
Accuracy: 1.0
Fold 8701:
Accuracy: 1.0
Fold 8702:
Accuracy: 1.0
Fold 8703:
Accuracy: 1.0
Fold 8704:
Accuracy: 1.0
Fold 8705:
Accuracy: 1.0
Fold 8706:
Accuracy: 1.0
Fold 8707:
Accuracy: 1.0
Fold 8708:
Accuracy: 1.0
Fold 8709:
Accuracy: 1.0
Fold 8710:
Accuracy: 1.0
Fold 8711:
Accuracy: 1.0
Fold 8712:
Accuracy: 1.0
Fold 8713:
Accuracy: 1.0
Fold 8714:
Accuracy: 1.0
Fold 8715:
Accuracy: 1.0
Fold 8716:
Accuracy: 0.5
Fold 8717:
Accuracy: 1.0
Fold 8718:
Accuracy: 1.0
Fold 8719:
Accuracy: 1.0
Fold 8720:
Accuracy: 1.0
Fold 8721:
Accuracy: 1.0
Fold 8722:
Accuracy: 1.0
Fold 8723:
Accuracy: 1.0
Fold 8724:
Accuracy: 1.0
Fold 8725:
Accuracy: 1.0
Fold 8726:
Accuracy: 1.0
Fold 8727:
Accuracy: 1.0
Fold 8728:
Accuracy: 1.0
Fold 8729:
Accuracy: 0.5
Fold 8730:
Accuracy: 1.0
Fold 8731:
Accuracy: 1.0
Fold 8732:
Accuracy: 1.0
Fold 8733:
Accuracy: 1.0
Fold 8734:
Accuracy: 1.0
Fold 8735:
Accuracy: 1.0
Fold 8736:
Accuracy: 1.0
Fold 8737:
Accuracy: 1.0
Fold 8738:
Accuracy: 1.0
Fold 8739:
Accuracy: 1.0
Fold 8740:
Accuracy: 1.0
Fold 8741:
Accuracy: 1.0
Fold 8742:
Accuracy: 1.0
Fold 8743:
Accuracy: 1.0
Fold 8744:
Accuracy: 1.0
Fold 8745:
Accuracy: 1.0
Fold 8746:
Accuracy: 1.0
Fold 8747:
Accuracy: 1.0
Fold 8748:
Accuracy: 1.0
Fold 8749:
Accuracy: 1.0
Fold 8750:
Accuracy: 1.0
Fold 8751:
Accuracy: 1.0
Fold 8752:
Accuracy: 1.0
Fold 8753:
Accuracy: 1.0
Fold 8754:
Accuracy: 1.0
Fold 8755:
Accuracy: 1.0
Fold 8756:
Accuracy: 1.0
Fold 8757:
Accuracy: 1.0
Fold 8758:
Accuracy: 1.0
Fold 8759:
Accuracy: 1.0
Fold 8760:
Accuracy: 1.0
Fold 8761:
Accuracy: 1.0
Fold 8762:
Accuracy: 0.5
Fold 8763:
Accuracy: 1.0
Fold 8764:
Accuracy: 1.0
Fold 8765:
Accuracy: 1.0
Fold 8766:
Accuracy: 1.0
Fold 8767:
Accuracy: 1.0
Fold 8768:
Accuracy: 1.0
Fold 8769:
Accuracy: 1.0
Fold 8770:
Accuracy: 1.0
Fold 8771:
Accuracy: 1.0
Fold 8772:
Accuracy: 1.0
Fold 8773:
Accuracy: 1.0
Fold 8774:
Accuracy: 1.0
Fold 8775:
Accuracy: 1.0
Fold 8776:
Accuracy: 1.0
Fold 8777:
Accuracy: 1.0
Fold 8778:
Accuracy: 1.0
Fold 8779:
Accuracy: 1.0
Fold 8780:
Accuracy: 1.0
Fold 8781:
Accuracy: 1.0
Fold 8782:
Accuracy: 1.0
Fold 8783:
Accuracy: 1.0
Fold 8784:
Accuracy: 1.0
Fold 8785:
Accuracy: 0.5
Fold 8786:
Accuracy: 1.0
Fold 8787:
Accuracy: 1.0
Fold 8788:
Accuracy: 1.0
Fold 8789:
Accuracy: 1.0
Fold 8790:
Accuracy: 1.0
Fold 8791:
Accuracy: 1.0
Fold 8792:
Accuracy: 1.0
Fold 8793:
Accuracy: 1.0
Fold 8794:
Accuracy: 1.0
Fold 8795:
Accuracy: 1.0
Fold 8796:
Accuracy: 1.0
Fold 8797:
Accuracy: 1.0
Fold 8798:
Accuracy: 0.5
Fold 8799:
Accuracy: 1.0
Fold 8800:
Accuracy: 1.0
Fold 8801:
Accuracy: 1.0
Fold 8802:
Accuracy: 1.0
Fold 8803:
Accuracy: 1.0
Fold 8804:
Accuracy: 1.0
Fold 8805:
Accuracy: 1.0
Fold 8806:
Accuracy: 1.0
Fold 8807:
Accuracy: 1.0
Fold 8808:
Accuracy: 1.0
Fold 8809:
Accuracy: 1.0
Fold 8810:
Accuracy: 1.0
Fold 8811:
Accuracy: 1.0
Fold 8812:
Accuracy: 1.0
Fold 8813:
Accuracy: 1.0
Fold 8814:
Accuracy: 1.0
Fold 8815:
Accuracy: 1.0
Fold 8816:
Accuracy: 1.0
Fold 8817:
Accuracy: 1.0
Fold 8818:
Accuracy: 1.0
Fold 8819:
Accuracy: 1.0
Fold 8820:
Accuracy: 1.0
Fold 8821:
Accuracy: 1.0
Fold 8822:
Accuracy: 1.0
Fold 8823:
Accuracy: 1.0
Fold 8824:
Accuracy: 1.0
Fold 8825:
Accuracy: 1.0
Fold 8826:
Accuracy: 1.0
Fold 8827:
Accuracy: 1.0
Fold 8828:
Accuracy: 1.0
Fold 8829:
Accuracy: 1.0
Fold 8830:
Accuracy: 0.5
Fold 8831:
Accuracy: 1.0
Fold 8832:
Accuracy: 1.0
Fold 8833:
Accuracy: 1.0
Fold 8834:
Accuracy: 1.0
Fold 8835:
Accuracy: 1.0
Fold 8836:
Accuracy: 1.0
Fold 8837:
Accuracy: 1.0
Fold 8838:
Accuracy: 1.0
Fold 8839:
Accuracy: 1.0
Fold 8840:
Accuracy: 1.0
Fold 8841:
Accuracy: 1.0
Fold 8842:
Accuracy: 1.0
Fold 8843:
Accuracy: 1.0
Fold 8844:
Accuracy: 1.0
Fold 8845:
Accuracy: 1.0
Fold 8846:
Accuracy: 1.0
Fold 8847:
Accuracy: 1.0
Fold 8848:
Accuracy: 1.0
Fold 8849:
Accuracy: 1.0
Fold 8850:
Accuracy: 1.0
Fold 8851:
Accuracy: 1.0
Fold 8852:
Accuracy: 1.0
Fold 8853:
Accuracy: 0.5
Fold 8854:
Accuracy: 1.0
Fold 8855:
Accuracy: 1.0
Fold 8856:
Accuracy: 1.0
Fold 8857:
Accuracy: 1.0
Fold 8858:
Accuracy: 1.0
Fold 8859:
Accuracy: 1.0
Fold 8860:
Accuracy: 1.0
Fold 8861:
Accuracy: 1.0
Fold 8862:
Accuracy: 1.0
Fold 8863:
Accuracy: 1.0
Fold 8864:
Accuracy: 1.0
Fold 8865:
Accuracy: 1.0
Fold 8866:
Accuracy: 0.5
Fold 8867:
Accuracy: 1.0
Fold 8868:
Accuracy: 1.0
Fold 8869:
Accuracy: 1.0
Fold 8870:
Accuracy: 1.0
Fold 8871:
Accuracy: 1.0
Fold 8872:
Accuracy: 1.0
Fold 8873:
Accuracy: 1.0
Fold 8874:
Accuracy: 1.0
Fold 8875:
Accuracy: 1.0
Fold 8876:
Accuracy: 1.0
Fold 8877:
Accuracy: 1.0
Fold 8878:
Accuracy: 1.0
Fold 8879:
Accuracy: 1.0
Fold 8880:
Accuracy: 1.0
Fold 8881:
Accuracy: 1.0
Fold 8882:
Accuracy: 1.0
Fold 8883:
Accuracy: 1.0
Fold 8884:
Accuracy: 1.0
Fold 8885:
Accuracy: 1.0
Fold 8886:
Accuracy: 1.0
Fold 8887:
Accuracy: 1.0
Fold 8888:
Accuracy: 1.0
Fold 8889:
Accuracy: 1.0
Fold 8890:
Accuracy: 1.0
Fold 8891:
Accuracy: 1.0
Fold 8892:
Accuracy: 1.0
Fold 8893:
Accuracy: 1.0
Fold 8894:
Accuracy: 1.0
Fold 8895:
Accuracy: 1.0
Fold 8896:
Accuracy: 1.0
Fold 8897:
Accuracy: 0.5
Fold 8898:
Accuracy: 1.0
Fold 8899:
Accuracy: 1.0
Fold 8900:
Accuracy: 1.0
Fold 8901:
Accuracy: 1.0
Fold 8902:
Accuracy: 1.0
Fold 8903:
Accuracy: 1.0
Fold 8904:
Accuracy: 1.0
Fold 8905:
Accuracy: 1.0
Fold 8906:
Accuracy: 1.0
Fold 8907:
Accuracy: 1.0
Fold 8908:
Accuracy: 1.0
Fold 8909:
Accuracy: 1.0
Fold 8910:
Accuracy: 1.0
Fold 8911:
Accuracy: 1.0
Fold 8912:
Accuracy: 1.0
Fold 8913:
Accuracy: 1.0
Fold 8914:
Accuracy: 1.0
Fold 8915:
Accuracy: 1.0
Fold 8916:
Accuracy: 1.0
Fold 8917:
Accuracy: 1.0
Fold 8918:
Accuracy: 1.0
Fold 8919:
Accuracy: 1.0
Fold 8920:
Accuracy: 0.5
Fold 8921:
Accuracy: 1.0
Fold 8922:
Accuracy: 1.0
Fold 8923:
Accuracy: 1.0
Fold 8924:
Accuracy: 1.0
Fold 8925:
Accuracy: 1.0
Fold 8926:
Accuracy: 1.0
Fold 8927:
Accuracy: 1.0
Fold 8928:
Accuracy: 1.0
Fold 8929:
Accuracy: 1.0
Fold 8930:
Accuracy: 1.0
Fold 8931:
Accuracy: 1.0
Fold 8932:
Accuracy: 1.0
Fold 8933:
Accuracy: 0.5
Fold 8934:
Accuracy: 1.0
Fold 8935:
Accuracy: 1.0
Fold 8936:
Accuracy: 1.0
Fold 8937:
Accuracy: 1.0
Fold 8938:
Accuracy: 1.0
Fold 8939:
Accuracy: 1.0
Fold 8940:
Accuracy: 1.0
Fold 8941:
Accuracy: 1.0
Fold 8942:
Accuracy: 1.0
Fold 8943:
Accuracy: 1.0
Fold 8944:
Accuracy: 1.0
Fold 8945:
Accuracy: 1.0
Fold 8946:
Accuracy: 1.0
Fold 8947:
Accuracy: 1.0
Fold 8948:
Accuracy: 1.0
Fold 8949:
Accuracy: 1.0
Fold 8950:
Accuracy: 1.0
Fold 8951:
Accuracy: 1.0
Fold 8952:
Accuracy: 1.0
Fold 8953:
Accuracy: 1.0
Fold 8954:
Accuracy: 1.0
Fold 8955:
Accuracy: 1.0
Fold 8956:
Accuracy: 1.0
Fold 8957:
Accuracy: 1.0
Fold 8958:
Accuracy: 1.0
Fold 8959:
Accuracy: 1.0
Fold 8960:
Accuracy: 1.0
Fold 8961:
Accuracy: 1.0
Fold 8962:
Accuracy: 1.0
Fold 8963:
Accuracy: 1.0
Fold 8964:
Accuracy: 0.5
Fold 8965:
Accuracy: 0.5
Fold 8966:
Accuracy: 0.5
Fold 8967:
Accuracy: 0.5
Fold 8968:
Accuracy: 0.5
Fold 8969:
Accuracy: 0.5
Fold 8970:
Accuracy: 0.5
Fold 8971:
Accuracy: 0.5
Fold 8972:
Accuracy: 0.5
Fold 8973:
Accuracy: 0.5
Fold 8974:
Accuracy: 0.5
Fold 8975:
Accuracy: 0.5
Fold 8976:
Accuracy: 0.5
Fold 8977:
Accuracy: 0.5
Fold 8978:
Accuracy: 0.5
Fold 8979:
Accuracy: 0.5
Fold 8980:
Accuracy: 0.5
Fold 8981:
Accuracy: 0.5
Fold 8982:
Accuracy: 0.5
Fold 8983:
Accuracy: 0.5
Fold 8984:
Accuracy: 0.5
Fold 8985:
Accuracy: 0.5
Fold 8986:
Accuracy: 0.0
Fold 8987:
Accuracy: 0.5
Fold 8988:
Accuracy: 0.5
Fold 8989:
Accuracy: 0.5
Fold 8990:
Accuracy: 0.5
Fold 8991:
Accuracy: 0.5
Fold 8992:
Accuracy: 0.5
Fold 8993:
Accuracy: 0.5
Fold 8994:
Accuracy: 0.5
Fold 8995:
Accuracy: 0.5
Fold 8996:
Accuracy: 0.5
Fold 8997:
Accuracy: 0.5
Fold 8998:
Accuracy: 0.5
Fold 8999:
Accuracy: 0.5
Fold 9000:
Accuracy: 0.5
Fold 9001:
Accuracy: 0.5
Fold 9002:
Accuracy: 0.5
Fold 9003:
Accuracy: 0.5
Fold 9004:
Accuracy: 0.5
Fold 9005:
Accuracy: 0.5
Fold 9006:
Accuracy: 0.5
Fold 9007:
Accuracy: 0.5
Fold 9008:
Accuracy: 0.5
Fold 9009:
Accuracy: 0.5
Fold 9010:
Accuracy: 0.5
Fold 9011:
Accuracy: 0.5
Fold 9012:
Accuracy: 0.5
Fold 9013:
Accuracy: 0.5
Fold 9014:
Accuracy: 0.5
Fold 9015:
Accuracy: 0.5
Fold 9016:
Accuracy: 0.5
Fold 9017:
Accuracy: 0.5
Fold 9018:
Accuracy: 0.5
Fold 9019:
Accuracy: 0.5
Fold 9020:
Accuracy: 0.5
Fold 9021:
Accuracy: 0.5
Fold 9022:
Accuracy: 0.5
Fold 9023:
Accuracy: 0.5
Fold 9024:
Accuracy: 0.5
Fold 9025:
Accuracy: 0.5
Fold 9026:
Accuracy: 0.5
Fold 9027:
Accuracy: 0.5
Fold 9028:
Accuracy: 0.5
Fold 9029:
Accuracy: 0.5
Fold 9030:
Accuracy: 1.0
Fold 9031:
Accuracy: 1.0
Fold 9032:
Accuracy: 1.0
Fold 9033:
Accuracy: 1.0
Fold 9034:
Accuracy: 1.0
Fold 9035:
Accuracy: 1.0
Fold 9036:
Accuracy: 1.0
Fold 9037:
Accuracy: 1.0
Fold 9038:
Accuracy: 1.0
Fold 9039:
Accuracy: 1.0
Fold 9040:
Accuracy: 1.0
Fold 9041:
Accuracy: 1.0
Fold 9042:
Accuracy: 1.0
Fold 9043:
Accuracy: 1.0
Fold 9044:
Accuracy: 1.0
Fold 9045:
Accuracy: 1.0
Fold 9046:
Accuracy: 1.0
Fold 9047:
Accuracy: 1.0
Fold 9048:
Accuracy: 1.0
Fold 9049:
Accuracy: 1.0
Fold 9050:
Accuracy: 1.0
Fold 9051:
Accuracy: 0.5
Fold 9052:
Accuracy: 1.0
Fold 9053:
Accuracy: 1.0
Fold 9054:
Accuracy: 1.0
Fold 9055:
Accuracy: 1.0
Fold 9056:
Accuracy: 1.0
Fold 9057:
Accuracy: 1.0
Fold 9058:
Accuracy: 1.0
Fold 9059:
Accuracy: 1.0
Fold 9060:
Accuracy: 1.0
Fold 9061:
Accuracy: 1.0
Fold 9062:
Accuracy: 1.0
Fold 9063:
Accuracy: 1.0
Fold 9064:
Accuracy: 0.5
Fold 9065:
Accuracy: 1.0
Fold 9066:
Accuracy: 1.0
Fold 9067:
Accuracy: 1.0
Fold 9068:
Accuracy: 1.0
Fold 9069:
Accuracy: 1.0
Fold 9070:
Accuracy: 1.0
Fold 9071:
Accuracy: 1.0
Fold 9072:
Accuracy: 1.0
Fold 9073:
Accuracy: 1.0
Fold 9074:
Accuracy: 1.0
Fold 9075:
Accuracy: 1.0
Fold 9076:
Accuracy: 1.0
Fold 9077:
Accuracy: 1.0
Fold 9078:
Accuracy: 1.0
Fold 9079:
Accuracy: 1.0
Fold 9080:
Accuracy: 1.0
Fold 9081:
Accuracy: 1.0
Fold 9082:
Accuracy: 1.0
Fold 9083:
Accuracy: 1.0
Fold 9084:
Accuracy: 1.0
Fold 9085:
Accuracy: 1.0
Fold 9086:
Accuracy: 1.0
Fold 9087:
Accuracy: 1.0
Fold 9088:
Accuracy: 1.0
Fold 9089:
Accuracy: 1.0
Fold 9090:
Accuracy: 1.0
Fold 9091:
Accuracy: 1.0
Fold 9092:
Accuracy: 1.0
Fold 9093:
Accuracy: 1.0
Fold 9094:
Accuracy: 1.0
Fold 9095:
Accuracy: 1.0
Fold 9096:
Accuracy: 1.0
Fold 9097:
Accuracy: 1.0
Fold 9098:
Accuracy: 1.0
Fold 9099:
Accuracy: 1.0
Fold 9100:
Accuracy: 1.0
Fold 9101:
Accuracy: 1.0
Fold 9102:
Accuracy: 1.0
Fold 9103:
Accuracy: 1.0
Fold 9104:
Accuracy: 1.0
Fold 9105:
Accuracy: 1.0
Fold 9106:
Accuracy: 1.0
Fold 9107:
Accuracy: 1.0
Fold 9108:
Accuracy: 1.0
Fold 9109:
Accuracy: 1.0
Fold 9110:
Accuracy: 1.0
Fold 9111:
Accuracy: 1.0
Fold 9112:
Accuracy: 1.0
Fold 9113:
Accuracy: 1.0
Fold 9114:
Accuracy: 1.0
Fold 9115:
Accuracy: 0.5
Fold 9116:
Accuracy: 1.0
Fold 9117:
Accuracy: 1.0
Fold 9118:
Accuracy: 1.0
Fold 9119:
Accuracy: 1.0
Fold 9120:
Accuracy: 1.0
Fold 9121:
Accuracy: 1.0
Fold 9122:
Accuracy: 1.0
Fold 9123:
Accuracy: 1.0
Fold 9124:
Accuracy: 1.0
Fold 9125:
Accuracy: 1.0
Fold 9126:
Accuracy: 1.0
Fold 9127:
Accuracy: 1.0
Fold 9128:
Accuracy: 0.5
Fold 9129:
Accuracy: 1.0
Fold 9130:
Accuracy: 1.0
Fold 9131:
Accuracy: 1.0
Fold 9132:
Accuracy: 1.0
Fold 9133:
Accuracy: 1.0
Fold 9134:
Accuracy: 1.0
Fold 9135:
Accuracy: 1.0
Fold 9136:
Accuracy: 1.0
Fold 9137:
Accuracy: 1.0
Fold 9138:
Accuracy: 1.0
Fold 9139:
Accuracy: 1.0
Fold 9140:
Accuracy: 1.0
Fold 9141:
Accuracy: 1.0
Fold 9142:
Accuracy: 1.0
Fold 9143:
Accuracy: 1.0
Fold 9144:
Accuracy: 1.0
Fold 9145:
Accuracy: 1.0
Fold 9146:
Accuracy: 1.0
Fold 9147:
Accuracy: 1.0
Fold 9148:
Accuracy: 1.0
Fold 9149:
Accuracy: 1.0
Fold 9150:
Accuracy: 1.0
Fold 9151:
Accuracy: 1.0
Fold 9152:
Accuracy: 1.0
Fold 9153:
Accuracy: 1.0
Fold 9154:
Accuracy: 1.0
Fold 9155:
Accuracy: 1.0
Fold 9156:
Accuracy: 1.0
Fold 9157:
Accuracy: 1.0
Fold 9158:
Accuracy: 1.0
Fold 9159:
Accuracy: 1.0
Fold 9160:
Accuracy: 1.0
Fold 9161:
Accuracy: 1.0
Fold 9162:
Accuracy: 1.0
Fold 9163:
Accuracy: 1.0
Fold 9164:
Accuracy: 1.0
Fold 9165:
Accuracy: 1.0
Fold 9166:
Accuracy: 1.0
Fold 9167:
Accuracy: 1.0
Fold 9168:
Accuracy: 1.0
Fold 9169:
Accuracy: 1.0
Fold 9170:
Accuracy: 1.0
Fold 9171:
Accuracy: 1.0
Fold 9172:
Accuracy: 1.0
Fold 9173:
Accuracy: 1.0
Fold 9174:
Accuracy: 1.0
Fold 9175:
Accuracy: 1.0
Fold 9176:
Accuracy: 1.0
Fold 9177:
Accuracy: 1.0
Fold 9178:
Accuracy: 0.5
Fold 9179:
Accuracy: 1.0
Fold 9180:
Accuracy: 1.0
Fold 9181:
Accuracy: 1.0
Fold 9182:
Accuracy: 1.0
Fold 9183:
Accuracy: 1.0
Fold 9184:
Accuracy: 1.0
Fold 9185:
Accuracy: 1.0
Fold 9186:
Accuracy: 1.0
Fold 9187:
Accuracy: 1.0
Fold 9188:
Accuracy: 1.0
Fold 9189:
Accuracy: 1.0
Fold 9190:
Accuracy: 1.0
Fold 9191:
Accuracy: 0.5
Fold 9192:
Accuracy: 1.0
Fold 9193:
Accuracy: 1.0
Fold 9194:
Accuracy: 1.0
Fold 9195:
Accuracy: 1.0
Fold 9196:
Accuracy: 1.0
Fold 9197:
Accuracy: 1.0
Fold 9198:
Accuracy: 1.0
Fold 9199:
Accuracy: 1.0
Fold 9200:
Accuracy: 1.0
Fold 9201:
Accuracy: 1.0
Fold 9202:
Accuracy: 1.0
Fold 9203:
Accuracy: 1.0
Fold 9204:
Accuracy: 1.0
Fold 9205:
Accuracy: 1.0
Fold 9206:
Accuracy: 1.0
Fold 9207:
Accuracy: 1.0
Fold 9208:
Accuracy: 1.0
Fold 9209:
Accuracy: 1.0
Fold 9210:
Accuracy: 1.0
Fold 9211:
Accuracy: 1.0
Fold 9212:
Accuracy: 1.0
Fold 9213:
Accuracy: 1.0
Fold 9214:
Accuracy: 1.0
Fold 9215:
Accuracy: 1.0
Fold 9216:
Accuracy: 1.0
Fold 9217:
Accuracy: 1.0
Fold 9218:
Accuracy: 1.0
Fold 9219:
Accuracy: 1.0
Fold 9220:
Accuracy: 1.0
Fold 9221:
Accuracy: 1.0
Fold 9222:
Accuracy: 1.0
Fold 9223:
Accuracy: 1.0
Fold 9224:
Accuracy: 1.0
Fold 9225:
Accuracy: 1.0
Fold 9226:
Accuracy: 1.0
Fold 9227:
Accuracy: 1.0
Fold 9228:
Accuracy: 1.0
Fold 9229:
Accuracy: 1.0
Fold 9230:
Accuracy: 1.0
Fold 9231:
Accuracy: 1.0
Fold 9232:
Accuracy: 1.0
Fold 9233:
Accuracy: 1.0
Fold 9234:
Accuracy: 1.0
Fold 9235:
Accuracy: 1.0
Fold 9236:
Accuracy: 1.0
Fold 9237:
Accuracy: 1.0
Fold 9238:
Accuracy: 1.0
Fold 9239:
Accuracy: 1.0
Fold 9240:
Accuracy: 0.5
Fold 9241:
Accuracy: 1.0
Fold 9242:
Accuracy: 1.0
Fold 9243:
Accuracy: 1.0
Fold 9244:
Accuracy: 1.0
Fold 9245:
Accuracy: 1.0
Fold 9246:
Accuracy: 1.0
Fold 9247:
Accuracy: 1.0
Fold 9248:
Accuracy: 1.0
Fold 9249:
Accuracy: 1.0
Fold 9250:
Accuracy: 1.0
Fold 9251:
Accuracy: 1.0
Fold 9252:
Accuracy: 1.0
Fold 9253:
Accuracy: 0.5
Fold 9254:
Accuracy: 1.0
Fold 9255:
Accuracy: 1.0
Fold 9256:
Accuracy: 1.0
Fold 9257:
Accuracy: 1.0
Fold 9258:
Accuracy: 1.0
Fold 9259:
Accuracy: 1.0
Fold 9260:
Accuracy: 1.0
Fold 9261:
Accuracy: 1.0
Fold 9262:
Accuracy: 1.0
Fold 9263:
Accuracy: 1.0
Fold 9264:
Accuracy: 1.0
Fold 9265:
Accuracy: 1.0
Fold 9266:
Accuracy: 1.0
Fold 9267:
Accuracy: 1.0
Fold 9268:
Accuracy: 1.0
Fold 9269:
Accuracy: 1.0
Fold 9270:
Accuracy: 1.0
Fold 9271:
Accuracy: 1.0
Fold 9272:
Accuracy: 1.0
Fold 9273:
Accuracy: 1.0
Fold 9274:
Accuracy: 1.0
Fold 9275:
Accuracy: 1.0
Fold 9276:
Accuracy: 1.0
Fold 9277:
Accuracy: 1.0
Fold 9278:
Accuracy: 1.0
Fold 9279:
Accuracy: 1.0
Fold 9280:
Accuracy: 1.0
Fold 9281:
Accuracy: 1.0
Fold 9282:
Accuracy: 1.0
Fold 9283:
Accuracy: 1.0
Fold 9284:
Accuracy: 1.0
Fold 9285:
Accuracy: 1.0
Fold 9286:
Accuracy: 1.0
Fold 9287:
Accuracy: 1.0
Fold 9288:
Accuracy: 1.0
Fold 9289:
Accuracy: 1.0
Fold 9290:
Accuracy: 1.0
Fold 9291:
Accuracy: 1.0
Fold 9292:
Accuracy: 1.0
Fold 9293:
Accuracy: 1.0
Fold 9294:
Accuracy: 1.0
Fold 9295:
Accuracy: 1.0
Fold 9296:
Accuracy: 1.0
Fold 9297:
Accuracy: 1.0
Fold 9298:
Accuracy: 1.0
Fold 9299:
Accuracy: 1.0
Fold 9300:
Accuracy: 1.0
Fold 9301:
Accuracy: 0.5
Fold 9302:
Accuracy: 1.0
Fold 9303:
Accuracy: 1.0
Fold 9304:
Accuracy: 1.0
Fold 9305:
Accuracy: 1.0
Fold 9306:
Accuracy: 1.0
Fold 9307:
Accuracy: 1.0
Fold 9308:
Accuracy: 1.0
Fold 9309:
Accuracy: 1.0
Fold 9310:
Accuracy: 1.0
Fold 9311:
Accuracy: 1.0
Fold 9312:
Accuracy: 1.0
Fold 9313:
Accuracy: 1.0
Fold 9314:
Accuracy: 0.5
Fold 9315:
Accuracy: 1.0
Fold 9316:
Accuracy: 1.0
Fold 9317:
Accuracy: 1.0
Fold 9318:
Accuracy: 1.0
Fold 9319:
Accuracy: 1.0
Fold 9320:
Accuracy: 1.0
Fold 9321:
Accuracy: 1.0
Fold 9322:
Accuracy: 1.0
Fold 9323:
Accuracy: 1.0
Fold 9324:
Accuracy: 1.0
Fold 9325:
Accuracy: 1.0
Fold 9326:
Accuracy: 1.0
Fold 9327:
Accuracy: 1.0
Fold 9328:
Accuracy: 1.0
Fold 9329:
Accuracy: 1.0
Fold 9330:
Accuracy: 1.0
Fold 9331:
Accuracy: 1.0
Fold 9332:
Accuracy: 1.0
Fold 9333:
Accuracy: 1.0
Fold 9334:
Accuracy: 1.0
Fold 9335:
Accuracy: 1.0
Fold 9336:
Accuracy: 1.0
Fold 9337:
Accuracy: 1.0
Fold 9338:
Accuracy: 1.0
Fold 9339:
Accuracy: 1.0
Fold 9340:
Accuracy: 1.0
Fold 9341:
Accuracy: 1.0
Fold 9342:
Accuracy: 1.0
Fold 9343:
Accuracy: 1.0
Fold 9344:
Accuracy: 1.0
Fold 9345:
Accuracy: 1.0
Fold 9346:
Accuracy: 1.0
Fold 9347:
Accuracy: 1.0
Fold 9348:
Accuracy: 1.0
Fold 9349:
Accuracy: 1.0
Fold 9350:
Accuracy: 1.0
Fold 9351:
Accuracy: 1.0
Fold 9352:
Accuracy: 1.0
Fold 9353:
Accuracy: 1.0
Fold 9354:
Accuracy: 1.0
Fold 9355:
Accuracy: 1.0
Fold 9356:
Accuracy: 1.0
Fold 9357:
Accuracy: 1.0
Fold 9358:
Accuracy: 1.0
Fold 9359:
Accuracy: 1.0
Fold 9360:
Accuracy: 1.0
Fold 9361:
Accuracy: 0.5
Fold 9362:
Accuracy: 1.0
Fold 9363:
Accuracy: 1.0
Fold 9364:
Accuracy: 1.0
Fold 9365:
Accuracy: 1.0
Fold 9366:
Accuracy: 1.0
Fold 9367:
Accuracy: 1.0
Fold 9368:
Accuracy: 1.0
Fold 9369:
Accuracy: 1.0
Fold 9370:
Accuracy: 1.0
Fold 9371:
Accuracy: 1.0
Fold 9372:
Accuracy: 1.0
Fold 9373:
Accuracy: 1.0
Fold 9374:
Accuracy: 0.5
Fold 9375:
Accuracy: 1.0
Fold 9376:
Accuracy: 1.0
Fold 9377:
Accuracy: 1.0
Fold 9378:
Accuracy: 1.0
Fold 9379:
Accuracy: 1.0
Fold 9380:
Accuracy: 1.0
Fold 9381:
Accuracy: 1.0
Fold 9382:
Accuracy: 1.0
Fold 9383:
Accuracy: 1.0
Fold 9384:
Accuracy: 1.0
Fold 9385:
Accuracy: 1.0
Fold 9386:
Accuracy: 1.0
Fold 9387:
Accuracy: 1.0
Fold 9388:
Accuracy: 1.0
Fold 9389:
Accuracy: 1.0
Fold 9390:
Accuracy: 1.0
Fold 9391:
Accuracy: 1.0
Fold 9392:
Accuracy: 1.0
Fold 9393:
Accuracy: 1.0
Fold 9394:
Accuracy: 1.0
Fold 9395:
Accuracy: 1.0
Fold 9396:
Accuracy: 1.0
Fold 9397:
Accuracy: 1.0
Fold 9398:
Accuracy: 1.0
Fold 9399:
Accuracy: 1.0
Fold 9400:
Accuracy: 1.0
Fold 9401:
Accuracy: 1.0
Fold 9402:
Accuracy: 1.0
Fold 9403:
Accuracy: 1.0
Fold 9404:
Accuracy: 1.0
Fold 9405:
Accuracy: 1.0
Fold 9406:
Accuracy: 1.0
Fold 9407:
Accuracy: 1.0
Fold 9408:
Accuracy: 1.0
Fold 9409:
Accuracy: 1.0
Fold 9410:
Accuracy: 1.0
Fold 9411:
Accuracy: 1.0
Fold 9412:
Accuracy: 1.0
Fold 9413:
Accuracy: 1.0
Fold 9414:
Accuracy: 1.0
Fold 9415:
Accuracy: 1.0
Fold 9416:
Accuracy: 1.0
Fold 9417:
Accuracy: 1.0
Fold 9418:
Accuracy: 1.0
Fold 9419:
Accuracy: 1.0
Fold 9420:
Accuracy: 0.5
Fold 9421:
Accuracy: 1.0
Fold 9422:
Accuracy: 1.0
Fold 9423:
Accuracy: 1.0
Fold 9424:
Accuracy: 1.0
Fold 9425:
Accuracy: 1.0
Fold 9426:
Accuracy: 1.0
Fold 9427:
Accuracy: 1.0
Fold 9428:
Accuracy: 1.0
Fold 9429:
Accuracy: 1.0
Fold 9430:
Accuracy: 1.0
Fold 9431:
Accuracy: 1.0
Fold 9432:
Accuracy: 1.0
Fold 9433:
Accuracy: 0.5
Fold 9434:
Accuracy: 1.0
Fold 9435:
Accuracy: 1.0
Fold 9436:
Accuracy: 1.0
Fold 9437:
Accuracy: 1.0
Fold 9438:
Accuracy: 1.0
Fold 9439:
Accuracy: 1.0
Fold 9440:
Accuracy: 1.0
Fold 9441:
Accuracy: 1.0
Fold 9442:
Accuracy: 1.0
Fold 9443:
Accuracy: 1.0
Fold 9444:
Accuracy: 1.0
Fold 9445:
Accuracy: 1.0
Fold 9446:
Accuracy: 1.0
Fold 9447:
Accuracy: 1.0
Fold 9448:
Accuracy: 1.0
Fold 9449:
Accuracy: 1.0
Fold 9450:
Accuracy: 1.0
Fold 9451:
Accuracy: 1.0
Fold 9452:
Accuracy: 1.0
Fold 9453:
Accuracy: 1.0
Fold 9454:
Accuracy: 1.0
Fold 9455:
Accuracy: 1.0
Fold 9456:
Accuracy: 1.0
Fold 9457:
Accuracy: 1.0
Fold 9458:
Accuracy: 1.0
Fold 9459:
Accuracy: 1.0
Fold 9460:
Accuracy: 1.0
Fold 9461:
Accuracy: 1.0
Fold 9462:
Accuracy: 1.0
Fold 9463:
Accuracy: 1.0
Fold 9464:
Accuracy: 1.0
Fold 9465:
Accuracy: 1.0
Fold 9466:
Accuracy: 1.0
Fold 9467:
Accuracy: 1.0
Fold 9468:
Accuracy: 1.0
Fold 9469:
Accuracy: 1.0
Fold 9470:
Accuracy: 1.0
Fold 9471:
Accuracy: 1.0
Fold 9472:

#2. Изучите функцию cross_validate(). Продемонстрируйте работу этой функции на тех же данных.

In [28]:
pd.DataFrame(cross_validate(LR(),x.values,y,cv = 10))

   fit_time  score_time  test_score
0  0.028435    0.001446    1.000000
1  0.030301    0.001307    0.933333
2  0.032148    0.001226    1.000000
3  0.065493    0.001344    1.000000
4  0.057972    0.001328    0.933333
5  0.037121    0.008534    0.933333
6  0.089345    0.001231    0.933333
7  0.035542    0.001390    1.000000
8  0.042849    0.001362    1.000000
9  0.029512    0.001314    1.000000

#3. Оцените при помощи кросс-валидации другие метрики эффективности для этой же модели.

In [36]:
get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'd2_absolute_error_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_max_error',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'neg_root_mean_squared_log_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_ovr',
 'roc_auc_ovr_weighted',
 'top_k_accuracy',
 'v_measure_score']

In [39]:
pd.DataFrame(cross_validate(LR(),x.values,y,cv = 10,scoring=('r2', 'f1_macro','recall_macro')))

   fit_time  score_time  test_r2  test_f1_macro  test_recall_macro
0  0.032613    0.008414      1.0        1.00000           1.000000
1  0.028738    0.007835      0.9        0.93266           0.933333
2  0.031467    0.007976      1.0        1.00000           1.000000
3  0.034061    0.007927      1.0        1.00000           1.000000
4  0.029355    0.011290      0.9        0.93266           0.933333
5  0.033735    0.008257      0.9        0.93266           0.933333
6  0.034182    0.009239      0.9        0.93266           0.933333
7  0.024208    0.007471      1.0        1.00000           1.000000
8  0.026729    0.009802      1.0        1.00000           1.000000
9  0.027076    0.007758      1.0        1.00000           1.000000

#4. Сравните кросс-валидированные результаты работы нескольких моделей на одних и тех же данных.

In [47]:
p1 = pd.DataFrame(cross_validate(LR(),x.values,y,cv = 10,scoring=('r2', 'f1_macro','recall_macro')))
p1.columns = [f'{i}_LR' for i in p1.columns]
p2 = pd.DataFrame(cross_validate(RFC(),x.values,y,cv = 10,scoring=('r2', 'f1_macro','recall_macro')))
p2.columns = [f'{i}_RFC' for i in p2.columns]
p3 = p2.join(p1)
p3.head()
p3['fit_time_diff'] = p3['fit_time_RFC'] - p3['fit_time_LR']
p3['test_r2_diff'] = p3['test_r2_RFC'] - p3['test_r2_LR']
p3['test_f1_diff'] = p3['test_f1_macro_RFC'] - p3['test_f1_macro_LR']
print(f'RFC - LR:')
p3[['fit_time_diff','test_r2_diff' ,'test_f1_diff']]

RFC - LR:

   fit_time_diff  test_r2_diff  test_f1_diff
0       0.190744           0.0      0.000000
1       0.100075           0.0      0.000000
2       0.086285           0.0      0.000000
3       0.109697          -0.1     -0.067340
4       0.062496           0.0      0.000000
5       0.124449           0.0      0.000000
6       0.102516          -0.1     -0.065993
7       0.128492           0.0      0.000000
8       0.103433           0.0      0.000000
9       0.076208           0.0      0.000000

#5. Повторите анализ на другом датасете: встроенном наборе данных о диабете.

In [68]:
get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'd2_absolute_error_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_max_error',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'neg_root_mean_squared_log_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_ovr',
 'roc_auc_ovr_weighted',
 'top_k_accuracy',
 'v_measure_score']

In [75]:
x,y = load_diabetes(as_frame=True).data,load_diabetes().target
display(x)
p1 = pd.DataFrame(cross_validate(LinReg(),x.values,y,cv = 10,scoring=('r2', 'neg_median_absolute_error','neg_max_error')))
p2 = pd.DataFrame(cross_validate(SVR(),x.values,y,cv = 10,scoring=('r2', 'neg_median_absolute_error','neg_max_error')))

p4 = pd.DataFrame()
for i in p1.columns:
  p4[f'{i}_diff'] = p1[i] - p2[i]

p1.columns = [f'{i}_LinReg' for i in p1.columns]
p2.columns = [f'{i}_SVR' for i in p2.columns]
p3 = p2.join(p1)
display(p3)

p4

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

,fit_time_SVR,score_time_SVR,test_r2_SVR,test_neg_median_absolute_error_SVR,test_neg_max_error_SVR,fit_time_LinReg,score_time_LinReg,test_r2_LinReg,test_neg_median_absolute_error_LinReg,test_neg_max_error_LinReg
0,0.069782,0.039415,0.151006,-49.015227,-185.702797,0.001753,0.010238,0.556146,-40.355154,-121.935303
1,0.110574,0.025183,0.099687,-50.236056,-112.400350,0.005687,0.036394,0.230558,-40.677735,-156.287075
2,0.109916,0.021289,0.140732,-36.243558,-169.122468,0.007948,0.026288,0.353577,-45.383667,-158.146863
3,0.094691,0.035159,0.142590,-55.821317,-176.968805,0.001863,0.020226,0.621908,-39.531314,-122.830831
4,0.063652,0.021234,0.201155,-47.252646,-136.534896,0.001561,0.019951,0.265873,-48.342418,-133.508531
5,0.024716,0.004712,0.175160,-56.977585,-195.793591,0.001378,0.013731,0.618198,-41.826692,-123.789575
6,0.017695,0.004557,0.175032,-63.412976,-167.192988,0.010753,0.018965,0.418151,-34.887195,-141.366653
7,0.017515,0.004508,0.067926,-45.520586,-156.752939,0.012747,0.008710,0.435137,-29.732496,-113.911146
8,0.018285,0.004522,0.159259,-68.054405,-162.597987,0.011767,0.002329,0.434362,-38.552063,-138.928652
9,0.017395,0.004554,0.200241,-51.218598,-149.717314,0.014265,0.018719,0.685693,-25.664099,-97.308094

,fit_time_diff,score_time_diff,test_r2_diff,test_neg_median_absolute_error_diff,test_neg_max_error_diff
0,-0.068030,-0.029177,0.405139,8.660074,63.767494
1,-0.104887,0.011211,0.130872,9.558322,-43.886726
2,-0.101968,0.004999,0.212845,-9.140108,10.975605
3,-0.092828,-0.014933,0.479318,16.290003,54.137974
4,-0.062091,-0.001284,0.064717,-1.089772,3.026366
5,-0.023338,0.009019,0.443038,15.150893,72.004016
6,-0.006942,0.014409,0.243120,28.525781,25.826335
7,-0.004768,0.004201,0.367211,15.788090,42.841793
8,-0.006518,-0.002193,0.275104,29.502342,23.669336
9,-0.003130,0.014166,0.485451,25.554499,52.409220

#6. Сделайте k-блочную перекрёстную проверку (KFold) модели логистической регрессии, предварительно стандартизировав данные. Для этого создайте конвейер с помощью make_pipeline из библиотеки sklearn.pipeline, который будет стандартизировать, а затем выполнять логистическую регрессию.

In [96]:
pipe = make_pipeline(SC(),LR())

folding = KFold(10, random_state=42,shuffle=True)

x,y = load_iris().data,load_iris().target

for i, (train_index, test_index) in enumerate(folding.split(x)):
    print(f"Fold {i}:")
    m = pipe.fit(x[train_index],y[train_index])
    print(f'Precision: {precision_score(y[test_index],m.predict(x[test_index]),average="macro")}')
    print(f'Recall:    {recall_score(y[test_index],m.predict(x[test_index]),average="macro")}')
    print()

Fold 0:
Precision: 1.0
Recall:    1.0

Fold 1:
Precision: 1.0
Recall:    1.0

Fold 2:
Precision: 1.0
Recall:    1.0

Fold 3:
Precision: 0.9523809523809524
Recall:    0.9333333333333332

Fold 4:
Precision: 1.0
Recall:    1.0

Fold 5:
Precision: 0.8666666666666667
Recall:    0.8888888888888888

Fold 6:
Precision: 0.8000000000000002
Recall:    0.8055555555555555

Fold 7:
Precision: 1.0
Recall:    1.0

Fold 8:
Precision: 1.0
Recall:    1.0

Fold 9:
Precision: 0.9523809523809524
Recall:    0.9523809523809524