In [19]:
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.linear_model import LogisticRegression as LRC
from sklearn.tree import DecisionTreeClassifier as Tree
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression as LR
from sklearn.preprocessing import PolynomialFeatures as PF
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler as SC
from sklearn.preprocessing import MinMaxScaler as MMS

#классификация
from sklearn.metrics import accuracy_score as acc
from sklearn.metrics import precision_score as pr
from sklearn.metrics import recall_score as rec
from sklearn.metrics import f1_score as f1
from sklearn.metrics import classification_report as report
from sklearn.metrics import confusion_matrix as cm
#регрессия
from sklearn.metrics import r2_score as r2
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_percentage_error as mape
from sklearn.metrics import mean_squared_log_error as msle
from sklearn.metrics import root_mean_squared_error as rmse
from sklearn.metrics import median_absolute_error as medae
from sklearn.metrics import max_error as maxe



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_wine
from sklearn.datasets import load_diabetes
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import fetch_california_housing
from sklearn.datasets import fetch_covtype
from sklearn.datasets import fetch_olivetti_faces

import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings("ignore", category=DataConversionWarning)

##1 Повторите анализ для других видов моделей. Используйте 5-10 разных классов моделей. Подсчитывайте только метрики на тестовой выборке

классы моделей:

1.KNN

2.LogReg

3.Tree

4.SVM

5.LinearRegression

6.PolynomialRegression

###классификация

In [9]:
p = load_breast_cancer(as_frame=True).frame
display(p.head())
display(p.info())
display(p.describe())

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  target                   569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

None

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000

In [14]:
p = load_breast_cancer()
x = p.data
y = p.target

def analyse (x,y,m):
  x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)
  m.fit(x_train,y_train)
  #y_train_pred = m.predict(x_train)
  y_test_pred = m.predict(x_test)
  #print(cm(y_train, y_train_pred))
  print(cm(y_test, y_test_pred))
  metrics = pd.DataFrame({
    "Test": [
        acc(y_test, y_test_pred),
        pr(y_test, y_test_pred,average='macro'),
        rec(y_test, y_test_pred,average='macro'),
        f1(y_test, y_test_pred,average='macro'),
    ],
    }, index = ["Accuracy", "Precision", "Recall", "F1"])
  display(metrics)
#1
print(f'KNN:')
m = KNN(n_neighbors=7)
analyse(x,y,m)
print(f'____________\n\n')
#2
print('LogReg:')
m = LRC(max_iter=10000)
analyse(x,y,m)
print(f'____________\n\n')
#3
print('Tree:')
m = Tree(max_depth = 10)
analyse(x,y,m)
print(f'____________\n\n')
#4
print('SVM:')
m = SVC(kernel = 'linear')
analyse(x,y,m)
print(f'____________\n\n')
#5
print('Random Forest:')
m = RFC()
analyse(x,y,m)
print(f'____________\n\n')

KNN:
[[41  4]
 [ 1 68]]

               Test
Accuracy   0.956140
Precision  0.960317
Recall     0.948309
F1         0.953534

____________


LogReg:
[[46  3]
 [ 0 65]]

               Test
Accuracy   0.973684
Precision  0.977941
Recall     0.969388
F1         0.972932

____________


Tree:
[[40  3]
 [ 4 67]]

               Test
Accuracy   0.938596
Precision  0.933117
Recall     0.936947
F1         0.934947

____________


SVM:
[[39  2]
 [ 3 70]]

               Test
Accuracy   0.956140
Precision  0.950397
Recall     0.955062
F1         0.952638

____________


Random Forest:
[[34  3]
 [ 0 77]]

               Test
Accuracy   0.973684
Precision  0.981250
Recall     0.959459
F1         0.969319

____________

###Регрессия

In [ ]:
p = load_diabetes(as_frame=True).frame
display(p.head())
display(p.info())
display(p.describe())

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
 10  target  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB

None

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,442.000000
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17,152.133484
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,77.093005
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01,25.000000
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02,87.000000
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03,140.500000
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02,211.500000
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01,346.000000

In [ ]:
p = load_diabetes(as_frame=True).frame
x = p.drop('target',axis=1)
y = p[['target']]

def analyse (x,y,m):
  x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)
  m.fit(x_train,y_train)
  #y_train_pred = m.predict(x_train)
  y_test_pred = m.predict(x_test)
  #print(cm(y_train, y_train_pred))
  #print(cm(y_test, y_test_pred))
  metrics = pd.DataFrame({
    "Test": [
        r2(y_test, y_test_pred),
        mae(y_test, y_test_pred),
        mse(y_test, y_test_pred),
    ],
    }, index = ["R2", "MAE", "MSE"])
  display(metrics)

#sc = SC()
#x = sc.fit_transform(x)
mms = MMS()
x = mms.fit_transform(x)

m = LR()
analyse(x,y,m)

pf = PF(degree=2)
x1 = pf.fit_transform(x)
m = LR()
analyse(x1,y,m)

m = SVR(kernel='sigmoid')
analyse(x,y,m)

m = Lasso()
analyse(x,y,m)

m = Ridge()
analyse(x,y,m)

            Test
R2      0.468514
MAE    47.166697
MSE  3230.248875

            Test
R2      0.284501
MAE    50.512396
MSE  4067.092418

            Test
R2     -0.059352
MAE    72.689077
MSE  7106.786366

            Test
R2      0.467420
MAE    46.759418
MSE  3400.723004

            Test
R2      0.426096
MAE    49.582244
MSE  3611.573388

##2 Повторите анализ для другого датасета по вашему выбору. Используйте несколько моделей для сравнения. Используйте датасет для множественной классификации.

In [15]:
p = load_wine(as_frame=True).frame
display(p.head())
display(p.info())
display(p.describe())

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  target                        178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

None

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

In [16]:
p = load_wine(as_frame=True).frame
x = p.drop('target',axis=1)
y = p[['target']]

def analyse (x,y,m):
  x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)
  m.fit(x_train,y_train)
  y_test_pred = m.predict(x_test)
  print(cm(y_test, y_test_pred))
  metrics = pd.DataFrame({
    "Test": [
        acc(y_test, y_test_pred),
        pr(y_test, y_test_pred,average='micro'),
        rec(y_test, y_test_pred,average='macro'),
        f1(y_test, y_test_pred,average='weighted'),
    ],
    }, index = ["Accuracy", "Precision", "Recall", "F1"])
  display(metrics)
#1
print(f'KNN:')
m = KNN(n_neighbors=7)
analyse(x,y,m)
print(f'____________\n\n')
#2
print('LogReg:')
m = LRC(max_iter=10000)
analyse(x,y,m)
print(f'____________\n\n')
#3
print('Tree:')
m = Tree(max_depth = 4)
analyse(x,y,m)
print(f'____________\n\n')
#4
print('SVM:')
m = SVC(kernel = 'linear')
analyse(x,y,m)
print(f'____________\n\n')
#5
print('Random Forest:')
m = RFC()
analyse(x,y,m)
print(f'____________\n\n')

KNN:
[[10  0  0]
 [ 1 13  2]
 [ 1  5  4]]

               Test
Accuracy   0.750000
Precision  0.750000
Recall     0.737500
F1         0.731283

____________


LogReg:
[[ 9  0  0]
 [ 2 14  0]
 [ 0  2  9]]

               Test
Accuracy   0.888889
Precision  0.888889
Recall     0.897727
F1         0.888889

____________


Tree:
[[10  0  0]
 [ 0 16  3]
 [ 1  0  6]]

               Test
Accuracy   0.888889
Precision  0.888889
Recall     0.899749
F1         0.892923

____________


SVM:
[[13  0  0]
 [ 0 14  0]
 [ 0  1  8]]

               Test
Accuracy   0.972222
Precision  0.972222
Recall     0.962963
F1         0.971884

____________


Random Forest:
[[13  0  0]
 [ 0 15  0]
 [ 0  0  8]]

           Test
Accuracy    1.0
Precision   1.0
Recall      1.0
F1          1.0

____________

## 3 Повторите анализ для датасета, предназначенного для решения задачи регрессии. Используйте все метрики качества регрессии, изученные на лекции. Постройте 5 - 10 разных моделей регрессии.

1.LinearReg

2.Polynomial

3.Ridge (L2)

4.Lasso (L1)

5.ElasticNet (L1 + L2)

6.SVR

In [ ]:
p = fetch_california_housing(as_frame=True).frame
display(p.head())
display(p.info())
display(p.describe())

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

None

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

In [ ]:
print(fetch_california_housing().DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33 (1997) 291-297

In [22]:
p = fetch_california_housing(as_frame=True)
x = p.data
y = p.target

def analyse (x,y,m):
  x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)
  m.fit(x_train,y_train)
  y_test_pred = m.predict(x_test)
  metrics = pd.DataFrame({
    "Test": [
        r2(y_test, y_test_pred),
        mae(y_test, y_test_pred),
        mse(y_test, y_test_pred),
        mape(y_test, y_test_pred),
        rmse(y_test, y_test_pred),
        medae(y_test, y_test_pred),
        maxe(y_test, y_test_pred)
    ],
    }, index = ["R2", "MAE", "MSE","MAPE","RMSE",'MedianError','MaxError'])
  display(metrics)
  print(f'\n\n')



sc = SC()
x = sc.fit_transform(x)
#mms = MMS()
#x = mms.fit_transform(x)

m = LR()
print(f'Linear Regression')
analyse(x,y,m)

pf = PF(degree=2)
x1 = pf.fit_transform(x)
m = LR()
print(f'Polynomial Regression')
analyse(x1,y,m)

m = SVR(kernel='rbf',C=5,epsilon = 0.05)
print(f'SVR')
analyse(x,y,m)

m = Lasso()
print(f'Lasso (L1)')
analyse(x,y,m)

m = Ridge()
print(f'Ridge (L2)')
analyse(x,y,m)

m = ElasticNet(l1_ratio=0.3)
print(f'ElasticNet (L1 + L2)')
analyse(x,y,m)

Linear Regression

                 Test
R2           0.596834
MAE          0.539029
MSE          0.529751
MAPE         0.319429
RMSE         0.727840
MedianError  0.425785
MaxError     4.176368

Polynomial Regression

                  Test
R2           -0.325688
MAE           0.484628
MSE           1.788439
MAPE          0.282293
RMSE          1.337325
MedianError   0.338205
MaxError     74.442038

SVR

                 Test
R2           0.746134
MAE          0.377790
MSE          0.338346
MAPE         0.202074
RMSE         0.581675
MedianError  0.239409
MaxError     4.131809

Lasso (L1)

                 Test
R2          -0.000042
MAE          0.910573
MSE          1.328523
MAPE         0.620184
RMSE         1.152616
MedianError  0.773054
MaxError     2.929956

Ridge (L2)

                 Test
R2           0.619071
MAE          0.525914
MSE          0.510295
MAPE         0.305896
RMSE         0.714350
MedianError  0.412636
MaxError     4.181759

ElasticNet (L1 + L2)

                 Test
R2           0.284469
MAE          0.774735
MSE          0.981830
MAPE         0.508485
RMSE         0.990873
MedianError  0.654031
MaxError     3.446527