In [ ]:
import numpy as np

In [ ]:
mx=np.zeros((4,4))
mx[0,:]+=1

In [ ]:
np.arange(3.0,step=0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
print(mx)

[[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

## 1

In [ ]:
mx = np.zeros((9,9))
mx[:,:] = np.array(np.arange(1,10))
#mx[0,:] = np.array(np.arange(1,10))
n = np.array(np.arange(1,10))
mx[:,:]*=n.reshape(9,1)
mx

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

## 2

In [ ]:
def F(N,fnum, q):
  n = np.array(np.arange(fnum,fnum+q*N,q))
  return np.diag(n)

F(3,1,0.3)

array([[1. , 0. , 0. ],
       [0. , 1.3, 0. ],
       [0. , 0. , 1.6]])

##3

In [ ]:
A = np.array(np.arange(1,26)).reshape(5,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## 4

In [ ]:
mx=np.zeros((4,4))
n = np.ones(4)
mx[0,:] = n
mx[:,0] = n
mx[-1,:] = n
mx[:,-1] = n
mx

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

## 5

In [ ]:
A = np.ones(5*5)
A[1::2]-=1
A = A.reshape(5,5) * 5
print(A,'\n')
'''
B = np.ones((5,5))
B -= np.diag(np.ones(4),-1)
B -= np.diag(np.ones(3),-2)
B -= np.diag(np.ones(2),-3)
B -= np.diag(np.ones(1),-4)
'''
B=np.triu((5,5))
B*=5
print(B)

print(f'\nThe determinant of A: {np.linalg.det(A)}\n',
      f'The determinant of B: {np.linalg.det(B)}\n',sep='')
try:
  print(np.linalg.inv(A))
except np.linalg.LinAlgError:
  print('нет обратной матрицы')
print(np.linalg.inv(B))

[[5. 0. 5. 0. 5.]
 [0. 5. 0. 5. 0.]
 [5. 0. 5. 0. 5.]
 [0. 5. 0. 5. 0.]
 [5. 0. 5. 0. 5.]]

[[25 25]
 [ 0 25]]

The determinant of A: 0.0
The determinant of B: 624.9999999999998

нет обратной матрицы
[[ 0.04 -0.04]
 [ 0.    0.04]]

## 6

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
p = pd.read_csv('/content/drive/MyDrive/nn fin/ML0.1 intro/data.csv')

## 7

In [ ]:
p.head()

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Shops_2,Price
0,11809,27,3.0,115.027311,NaN,10.0,4,10.0,2014,0.075424,B,B,11,3097,0,NaN,0,0,B,305018.871089
1,3013,22,1.0,39.832524,23.169223,8.0,7,8.0,1966,0.118537,B,B,30,6207,1,1183.0,1,0,B,177734.553407
2,8215,1,3.0,78.342215,47.671972,10.0,2,17.0,1988,0.025609,B,B,33,5261,0,240.0,3,1,B,282078.720850
3,2352,1,1.0,40.409907,NaN,1.0,10,22.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,168106.007630
4,13866,94,2.0,64.285067,38.562517,9.0,16,16.0,1972,0.282798,B,B,33,8667,2,NaN,0,6,B,343995.102962

In [ ]:
p.iloc[:-6:-1]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Shops_2,Price
9999,7202,94,1.0,35.815476,22.301367,6.0,9,9.0,1975,0.127376,B,B,43,8429,3,NaN,3,9,B,177685.627486
9998,14561,21,1.0,32.330292,22.326870,5.0,3,9.0,1969,0.194489,B,B,47,8004,3,125.0,3,5,B,171842.411855
9997,2795,178,1.0,29.648057,16.555363,5.0,3,5.0,1958,0.460556,B,B,20,4386,14,NaN,1,5,B,165953.912580
9996,16265,27,2.0,64.307684,37.038420,9.0,13,0.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,199715.148807
9995,1260,61,2.0,49.090728,33.272626,6.0,3,12.0,1981,0.300323,B,B,52,10311,6,NaN,1,9,B,119367.455796

## 8 !

In [ ]:
print(p.shape)
print(p.dtypes)

(10000, 20)
Id                 int64
DistrictId         int64
Rooms            float64
Square           float64
LifeSquare       float64
KitchenSquare    float64
Floor              int64
HouseFloor       float64
HouseYear          int64
Ecology_1        float64
Ecology_2         object
Ecology_3         object
Social_1           int64
Social_2           int64
Social_3           int64
Healthcare_1     float64
Helthcare_2        int64
Shops_1            int64
Shops_2           object
Price            float64
dtype: object

## 9

In [ ]:
p.drop(['DistrictId'])

KeyError: "['DistrictId'] not found in axis"